Numpy

*Numpy stands for Numerical python.
*Numpy is a Python library.
*It used for working with arrays.
*Numpy provides a powerful N-dimensional array object.
*Numpy is a 50x faster than standard python lists.

In [1]:
 pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [127]:
import numpy as np

initialize array

In [128]:
a=np.array([1,2,3],dtype="int16") 

with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes

In [129]:
print("one dimensional array :",a)

one dimensional array : [1 2 3]


In [130]:
b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


Get Dimension

In [131]:
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)

dimension of a : 1
dimension of b : 2


Get Shape

In [132]:
print("shape of a :",a.shape) 

shape of a : (3,)


its a vector so its tellings us one dimension 

In [133]:
print("shape of b :",b.shape)

shape of b : (2, 4)


Get  Type

In [134]:
print("a type is :",a.dtype)

a type is : int16


Get Size

In [135]:
print("size of a :",a.size)

size of a : 3


total size

In [136]:
print("a item size :",a.itemsize) 

a item size : 2


size of single element in the array .i,e in bytes

In [137]:
print("total size is a:",a.size*a.itemsize)

total size is a: 6


Get specific row 

In [138]:
print("row :",b[1,0:1]);

row : [2.1]


Get specific column[:,column]

In [139]:
print("column :",b[:,1])

column : [2. 3.]


In [140]:
print("subset of specific row",b[1,1::2])

subset of specific row [3.  4.5]


change element

In [141]:
b[1,2]=8
print(b)

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


In [142]:
b[:,2]=[9,4]
b

array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

In [143]:
b.dtype

dtype('float64')

In [144]:
import math
math.sqrt(4)

2.0

In [145]:
int(1.2)

1

# 3-d example 

In [146]:
c=np.array([[
    [1,2,5],
    [3,4,5]
    ],
    [[5,6,6],
     [7,8,7]
    ]
])
    
        

In [147]:
c

array([[[1, 2, 5],
        [3, 4, 5]],

       [[5, 6, 6],
        [7, 8, 7]]])

In [148]:
type(c)

numpy.ndarray

In [149]:
c.ndim

3

In [150]:
c.shape

(2, 2, 3)

In [151]:
c.size

12

##calclate the memory space took for c numpy array 

In [152]:
c.itemsize

8

In [153]:
c.itemsize*c.size

96

In [154]:
c.dtype

dtype('int64')

In [155]:
#get specific elements (work outside in)
print("Specified element is :",c[0,0,1])

Specified element is : 2


In [156]:
c[1,1,2]=100
c

array([[[  1,   2,   5],
        [  3,   4,   5]],

       [[  5,   6,   6],
        [  7,   8, 100]]])

initialize different types of  Arrays

In [157]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [158]:
zm = np.zeros((3,4))

In [159]:
zm

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [160]:
zm.ndim

2

In [161]:
zm.shape

(3, 4)

In [162]:
zm.size

12

### All 1's matrix 

In [163]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [164]:
np.ones((3,3),dtype = "int16")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [165]:
ones = np.ones((3,3),dtype = "int16")

In [166]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [167]:
ones[1,1] = 100
ones

array([[  1,   1,   1],
       [  1, 100,   1],
       [  1,   1,   1]], dtype=int16)

Any other number

In [168]:
np.full(ones.shape,88)

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [169]:
np.full(ones.shape,10000000000000)

array([[10000000000000, 10000000000000, 10000000000000],
       [10000000000000, 10000000000000, 10000000000000],
       [10000000000000, 10000000000000, 10000000000000]])

In [170]:
np.full(ones.shape,88,dtype = "float")

array([[88., 88., 88.],
       [88., 88., 88.],
       [88., 88., 88.]])

In [171]:
m100 = np.full(ones.shape,88,dtype = "float")
m100

array([[88., 88., 88.],
       [88., 88., 88.],
       [88., 88., 88.]])

### Reuse the already existing array and assign one value to each elements    

In [172]:
np.full_like(m100,200,dtype = "float")

array([[200., 200., 200.],
       [200., 200., 200.],
       [200., 200., 200.]])

Random matrix

In [173]:
np.random.random_sample(m100.shape)

array([[0.55758661, 0.807071  , 0.36758585],
       [0.43268843, 0.21114504, 0.09737396],
       [0.64370812, 0.78648732, 0.27270351]])

In [174]:
np.random.random_sample((2,3))

array([[0.55332095, 0.70341765, 0.3073616 ],
       [0.62377896, 0.21748257, 0.89930699]])

In [175]:
np.random.rand(2,3)

array([[0.89389648, 0.15848961, 0.59485092],
       [0.32323521, 0.9764929 , 0.03300218]])

In [177]:
np.random.randint(6,9,size=(3,3))

array([[7, 6, 6],
       [7, 6, 6],
       [6, 6, 8]], dtype=int32)

generate identity matrix only one argument bcoz identity matrix is a 

In [182]:
np.identity(6)   # 5,5

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])